sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TZ=UTC

install:
  - pip install coveralls
  - pip install wheel
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - flake8 molo
  - molo scaffold testapp --require molo.surveys
  - flake8 testapp
  - cp local_test_settings.py testapp/testapp/settings/local.py
  - cp molo/surveys/tests/*.html testapp/testapp/templates/core/
  - pip install -e testapp
  - py.test --cov=molo.surveys --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Praekelt
  password:
    secure: "generate with travis encrypt"
  on:
    tags: true
    all_branches: true
