sudo: false
language: python
python:
  - "3.6"
cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TZ=UTC

install:
  - pip install twine
  - pip install --upgrade pip --cache-dir $HOME/.pip-cache/
  - pip install coveralls coverage --cache-dir $HOME/.pip-cache/
  - pip install flake8 --cache-dir $HOME/.pip-cache/
  - pip install -r requirements-dev.txt --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
script:
  - flake8 molo
  - molo scaffold testapp --require molo.surveys --include molo.surveys ^surveys/
  - cp local_test_settings.py testapp/testapp/settings/local.py
  - mkdir testapp/testapp/templates/
  - mkdir testapp/testapp/templates/core
  - cp molo/surveys/test_templates/*.html testapp/testapp/templates/core/
  - cp molo/surveys/test_templates/base.html testapp/testapp/templates/base.html
  - flake8 testapp
  - pip install -e testapp
  - py.test --cov=molo.surveys --cov-report=term

after_success:
  - coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Praekelt
  password:
    secure: "mYNMALYTSZUK/GiFddyjyq4EP1QrbEPovYnzONbs2IImJHje3ZQlUITJc20dR3heshNJWMBmNufryLdnS5U1HXjCifnHYK8rZ5nQIOpf3wJwzjM13w61yIdGTsqbBURz7dy+l0JnNcmWpgbPSRJU+Qtuv5zn647Jw7A9pzGHvH/LyOS4O/3lHoLENUKPIwPIu//hTgmz5VzTIXuKzzNQHNSHALzs7saU+nEx7qwB24ZASScEomgulb/SVZ/d3oAdHfmgz6042vgB4vRB1AxuD6w8hh/mPnZbtfSCzsyn3QlT6Qeh6LFGwsVZsJMMZSbErJMMk+uB9Hqi8tzu61w94lbAFzWAMW6NNHnaJsuq4pO03LPPyB5a1ex4hyH+1UmcVOylzCCrajH4QM2N/b1wbqPt9/C1nFEUrF1T4uCWLaFmUcTZT1K0oJZhDadCAsGHNBL0x1Il+zMXpLO59ECt4TvvMfvbmW5BUPiEL6JfWvSCb053o0A6NsTzzGOaQHWPBSZkRoUrjASf6MiS8h65GcbbssgH97da4QpXWhMUVkuo9gbA1BD4AGSgjALIYh/IHNOYfvsPla6Upl5rsiwJpYdVgIeBZJcO91N5eR3dqDmqhVKDO3HatX4c3UivsX7yXaXv73wD6l9AiHvgOkirzfzvmgfDPi4I8LcVKWmfjUU="
  on:
    tags: true
    python: 3.6
