# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_override-512-char-limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GASurveySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_tag_manager_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='GA Tag Manager ID')),
                ('ci', models.CharField(max_length=255, unique=True, verbose_name='Campaign ID')),
                ('cn', models.CharField(max_length=255, verbose_name='Name')),
                ('cc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Content')),
                ('ck', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords')),
                ('cm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Medium')),
                ('cs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Source')),
                ('survey', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_ga_analytics', to='surveys.MoloSurveyPage', unique=True)),
            ],
        ),
    ]
